server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: discussions
          uri: lb://discussions
          predicates:
            - Path=/api/forum/**
        - id: advertisement
          uri: lb://advertisement
          predicates:
            - Path=/api/advertisement/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true