server:
  port: 8080
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: api_gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: discussions
          uri: lb://discussions
          predicates:
            - Path=/api/forum/**
        - id: advertisement
          uri: lb://advertisement
          predicates:
            - Path=/api/advertisement/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: ui
          uri: http://localhost:4200
          predicates:
            - Path=/index.html,/*.js,/*.css
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true